<?php
    /* @var $this Zhupanyn_Localstorage_Block_Storage */
    $productArray = $this->getProductRegistry();
?>
<script type="text/javascript">

    var productId = '<?=$productArray['product_id']?>';
    var localstorageUrlAjax = '<?=$this->getUrl('zhupanyn_localstorage/ajax/products')?>';

    if (productId != 0) {

        //localStorage.removeItem("zhupanyn_localstorage_product_viewed");

        ZhupanynLocalstorage.productObject = {
            product_id: productId,
            product_url: '<?=$productArray['product_url']?>',
            img_src: '<?=$productArray['img_src']?>',
            img_alt: '<?=$productArray['img_alt']?>',
            product_name: '<?=$productArray['product_name']?>',
        };

        ZhupanynLocalstorage.pageSize = '<?=$this->getPageSize()?>';
        ZhupanynLocalstorage.time = '<?=$this->helper('zhupanyn_localstorage')->getTime()?>';
        ZhupanynLocalstorage.domain = '<?=$this->helper('zhupanyn_localstorage')->getDomain()?>';

        ZhupanynLocalstorage.currentStorage(localstorageUrlAjax);

    }

</script>
