<?php
/* @var $this Mage_Reports_Block_Product_Viewed */
$tttt = 1;
?>
<div id="recently-viewed-wrapper" class="block block-list block-viewed" style="display: none;" >
    <div class="block-title">
        <strong><span><?php echo $this->__('Recently Viewed Products') ?></span></strong>
    </div>
    <div class="block-content">
        <ol id="recently-viewed-items" class="mini-products-list"></ol>
        <script type="text/javascript">decorateList('recently-viewed-items');</script>
    </div>
</div>
<div id="recently-viewed-items-test"></div>

<script type="text/javascript">

    var zh_ls_url_ajax = '<?=$this->getUrl('zhupanyn_localstorage/ajax/products')?>';

    $j(function(){

        zhupanyn_localstorage.time = '<?=$this->helper('zhupanyn_localstorage')->getTime()?>';
        zhupanyn_localstorage.domain = '<?=$this->helper('zhupanyn_localstorage')->getDomain()?>';

        //localStorage.removeItem("zhupanyn_localstorage_product_viewed");
        var storage =  zhupanyn_localstorage.getJsonStorage();
        zhupanyn_localstorage.currentStorage(storage, zh_ls_url_ajax);

    })

</script>